name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build TypeScript
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Configure npm for semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Ensure npm auth file exists so semantic-release can publish with NPM_TOKEN
          printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" > ~/.npmrc
          # Also set NODE_AUTH_TOKEN (some plugins/readers expect this env var)
          echo "NODE_AUTH_TOKEN=${NPM_TOKEN}" >> $GITHUB_ENV

      - name: Semantic Release
        run: bun run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
