name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Bundle CLI
        run: bun run bundle-cli

      - name: Run tests
        run: bun test --coverage

      - name: Test CLI commands
        run: |
          # Ensure CLI is built and executable
          chmod +x index.js
          node index.js --version
          node index.js --help
          node index.js analyze --help
          node index.js stats --help
          node index.js export --help

      - name: Test MCP server startup
        run: |
          cd packages/mcp && bun run build
          timeout 5s bun run dist/server.js || true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20'
        with:
          file: ./coverage/lcov.info
